/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static controlador.Constantes.USER;
import controlador.conexion;
import modelo.Control_preguntas;
import modelo.Control_registroRoot;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Control_login;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Ali Guerrero
 */
public class Interfaz_RegistroLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    Control_preguntas cr = new Control_preguntas();
    private  boolean estadoPermiso = false;
    private boolean estadoUser = false;
    public Interfaz_RegistroLogin() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.iconVeri1.setVisible(false);
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(this.iconVeri1, "src/imagenes/circulo.png");
        Object[] pregunta = cr.combox("preguntas_seg","pregunta");
        
        this.comboPre.removeAllItems();
        comboPre.addItem("Seleccionar...");
        for(int i=0;i<pregunta.length;i++){
            comboPre.addItem(pregunta[i].toString());
            
        }
        if (estadoPermiso == false) {
            this.inhabilitarCampo();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        campoCedula = new javax.swing.JTextField();
        campoUser = new javax.swing.JTextField();
        campoPass = new javax.swing.JPasswordField();
        campoPass2 = new javax.swing.JPasswordField();
        comboPre = new javax.swing.JComboBox<>();
        campoRes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        iconVeri1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        passRoot = new javax.swing.JPasswordField();
        btnActivarRoot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombres: ");

        jLabel2.setText("Apellidos: ");

        jLabel3.setText("Cedula de indentidad: ");

        jLabel4.setText("Username: ");

        jLabel5.setText("Password: ");

        jLabel6.setText("Confirmar Password: ");

        jLabel7.setText("Pregunta secreta: ");

        jLabel8.setText("Respuesta: ");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });

        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });
        campoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoKeyTyped(evt);
            }
        });

        campoCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCedulaKeyTyped(evt);
            }
        });

        campoUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoUserKeyReleased(evt);
            }
        });

        campoPass.setText("jPasswordField1");
        campoPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPassMouseClicked(evt);
            }
        });
        campoPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPassActionPerformed(evt);
            }
        });

        campoPass2.setText("jPasswordField2");
        campoPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPass2MouseClicked(evt);
            }
        });
        campoPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPass2ActionPerformed(evt);
            }
        });
        campoPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoPass2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPass2KeyReleased(evt);
            }
        });

        comboPre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));

        campoRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoResActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("REGISTRO DE USUARIO");

        iconVeri1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Codigo Root: ");

        passRoot.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passRoot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passRootMouseClicked(evt);
            }
        });
        passRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passRootActionPerformed(evt);
            }
        });

        btnActivarRoot.setText("Activar");
        btnActivarRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarRootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addComponent(passRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActivarRoot)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(passRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivarRoot))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(campoNombre)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoPass2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(campoCedula)
                                    .addComponent(campoUser)
                                    .addComponent(campoPass)
                                    .addComponent(comboPre, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoRes))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconVeri1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel9)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(campoPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(iconVeri1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoActionPerformed

    private void campoPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPassActionPerformed

    private void campoResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoResActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nom,ape,cedu,user,pass,res;
        int pre,sta;
        
        if (this.campoPass.getText().equals(this.campoPass2.getText())) {
            
            nom = this.campoNombre.getText();
            ape = this.campoApellido.getText();
            cedu = this.campoCedula.getText();
            user = this.campoUser.getText();
            pass = DigestUtils.md5Hex(this.campoPass.getText());
            pre  = this.comboPre.getSelectedIndex();
            res  = this.campoRes.getText();
            sta = USER;
            
            
            Control_login cl = new Control_login(nom,ape,cedu,user,pass,pre,res,sta);
            
            if (!nom.equals("") || !ape.equals("") || !cedu.equals("") || !user.equals("") || !pass.equals("") || pre!=0 || !res.equals("") || sta !=0)
            {   
                if (this.estadoUser == false) {
                    JOptionPane.showMessageDialog(null, "Existe un Usuario registrado con el mismo Username, por favor cambiar!!!", "Validando Datos",
                    JOptionPane.ERROR_MESSAGE);
                    this.campoUser.setText("");
                    this.revalidate();
                }else{
                    if(cl.ingresar_login())
                    {
                        JOptionPane.showMessageDialog(null,"El usuario se registro con exito","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                        limpiar();
                        this.inhabilitarCampo();
                        this.iconVeri1.setVisible(false);
                        this.revalidate();

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Error al registar el usuario ","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
           else{
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios");  
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Verifique los datos a registrar, no deje campos vacios¡ ","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void campoPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPassMouseClicked
        // TODO add your handling code here:
        
        this.campoPass.setText("");
        if (this.campoPass.getText().equals("")) {
            this.iconVeri1.setVisible(false);   
        }
        
    }//GEN-LAST:event_campoPassMouseClicked

    private void campoPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPass2MouseClicked
        // TODO add your handling code here:
        this.campoPass2.setText("");
        
    }//GEN-LAST:event_campoPass2MouseClicked

    private void campoPass2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPass2KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoPass2KeyPressed
    
    private void campoPass2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPass2KeyReleased
        // TODO add your handling code here:
       
        if (this.campoPass2.getText().equals(this.campoPass.getText())) {
            this.iconVeri1.setVisible(true);
        }else{
            this.iconVeri1.setVisible(false);
        }
        
    }//GEN-LAST:event_campoPass2KeyReleased

    private void campoCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCedulaKeyTyped
        // TODO add your handling code here:
             	
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 97 && k <= 122 || k >= 65 && k <= 255 || k >= 32 && k <= 47 || k >= 58 && k <= 64) {//Si el caracter ingresado es una letra
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
        JOptionPane.showMessageDialog(null, "No puede ingresar letras, ni carateres especiales!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_campoCedulaKeyTyped

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 32 && k <= 64 || k >= 91 && k <= 96 || k >= 123 && k <= 255) {//Si el caracter ingresado es una letra
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
        JOptionPane.showMessageDialog(null, "No puede ingresar numeros, ni caracteres especiales!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_campoNombreKeyTyped

    private void campoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 32 && k <= 64 || k >= 91 && k <= 96 || k >= 123 && k <= 255) {//Si el caracter ingresado es una letra
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
        JOptionPane.showMessageDialog(null, "No puede ingresar numeros, ni caracteres especiales!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_campoApellidoKeyTyped

    private void passRootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passRootMouseClicked
        // TODO add your handling code here:
        this.passRoot.setText("");
    }//GEN-LAST:event_passRootMouseClicked

    private void passRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passRootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passRootActionPerformed

    private void campoPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPass2ActionPerformed

    private void btnActivarRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarRootActionPerformed
        // TODO add your handling code here:
        String passR =  DigestUtils.md5Hex(this.passRoot.getText());
        Control_registroRoot cr = new Control_registroRoot(null,null,null,null,null,null,0,null);
        if (this.passRoot.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo codigo root esta vacio!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }else{
            if (cr.consulta_root_id(passR) == null) {
                JOptionPane.showMessageDialog(null, "Codigo Root Invalido!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
            }else{
                this.habilitarCampo();
                this.estadoPermiso = true;
                this.revalidate();
            }
        }
    }//GEN-LAST:event_btnActivarRootActionPerformed

    private void campoUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUserKeyReleased
        // TODO add your handling code here:
        
        Control_login cl = new Control_login(null,null,null,null,null,0,null,0);
        if (cl.consulta_loginUSER(this.campoUser.getText()) == null) {
            this.campoUser.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            this.estadoUser = true;
        }else{
             this.campoUser.setBorder(BorderFactory.createLineBorder(Color.RED));
             this.estadoUser = false;
        }
    }//GEN-LAST:event_campoUserKeyReleased
    private void inhabilitarCampo(){
        this.campoNombre.setEnabled(false);
        this.campoApellido.setEnabled(false);
        this.campoCedula.setEnabled(false);
        this.campoUser.setEnabled(false);
        this.campoPass.setEnabled(false);
        this.campoPass2.setEnabled(false);
        this.comboPre.setEnabled(false);
        this.campoRes.setEnabled(false);
        this.btnRegistrar.setEnabled(false);
    }
    private void habilitarCampo(){
        this.campoNombre.setEnabled(true);
        this.campoApellido.setEnabled(true);
        this.campoCedula.setEnabled(true);
        this.campoUser.setEnabled(true);
        this.campoPass.setEnabled(true);
        this.campoPass2.setEnabled(true);
        this.comboPre.setEnabled(true);
        this.campoRes.setEnabled(true);
        this.btnRegistrar.setEnabled(true);
    }
    public void limpiar(){
        this.campoNombre.setText("");
        this.campoApellido.setText("");
        this.campoCedula.setText("");
        this.campoUser.setText("");
        this.campoPass.setText("");
        this.campoPass2.setText("");
        this.comboPre.setSelectedIndex(0);
        this.campoRes.setText("");
        this.passRoot.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_RegistroLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActivarRoot;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JTextField campoApellido;
    public javax.swing.JTextField campoCedula;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JPasswordField campoPass;
    public javax.swing.JPasswordField campoPass2;
    public javax.swing.JTextField campoRes;
    public javax.swing.JTextField campoUser;
    public javax.swing.JComboBox<String> comboPre;
    public javax.swing.JLabel iconVeri1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField passRoot;
    // End of variables declaration//GEN-END:variables
}
