/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static controlador.Constantes.ADMIN;
import controlador.conexion;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.Control_login;
import modelo.Control_preguntas;
import modelo.Control_registroRoot;
import org.apache.commons.codec.digest.DigestUtils;
import rsscalelabel.RSScaleLabel;

/**
 *
 * @author Ali Guerrero
 */
public class Interfaz_RegistroRoot extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_RegistroRoot
     */
    
    Control_preguntas cr = new Control_preguntas();
    RSScaleLabel rs = new RSScaleLabel();
    private boolean estadoUser = false;
    public Interfaz_RegistroRoot() {
        initComponents();
        this.iconVeri1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Registro de super usuarios");
        Object[] pregunta = cr.combox("preguntas_seg","pregunta");
        
        this.comboPre.removeAllItems();
        comboPre.addItem("Seleccionar...");
        for(int i=0;i<pregunta.length;i++){
            comboPre.addItem(pregunta[i].toString());  
        }
        rs.setScaleLabel(this.iconVeri1, "src/imagenes/circulo.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        campoCRoot = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        campoCedula = new javax.swing.JTextField();
        campoPass = new javax.swing.JPasswordField();
        campoPass2 = new javax.swing.JPasswordField();
        campoUser = new javax.swing.JTextField();
        btnRecuperar = new javax.swing.JButton();
        iconVeri1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboPre = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        campoRes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Super Usuarios");

        jLabel2.setText("Nombres: ");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });

        jLabel3.setText("Apellidos: ");

        jLabel4.setText("Cedula de Identidad: ");

        jLabel5.setText("Username: ");

        jLabel6.setText("Contraseña: ");

        jLabel7.setText("Confirmar contraseña: ");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CODIGO ROOT: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoCRoot)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoCRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        campoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoKeyTyped(evt);
            }
        });

        campoCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCedulaKeyTyped(evt);
            }
        });

        campoPass.setText("jPasswordField1");
        campoPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPassMouseClicked(evt);
            }
        });
        campoPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPassActionPerformed(evt);
            }
        });

        campoPass2.setText("jPasswordField2");
        campoPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPass2MouseClicked(evt);
            }
        });
        campoPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPass2ActionPerformed(evt);
            }
        });
        campoPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPass2KeyReleased(evt);
            }
        });

        campoUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoUserKeyReleased(evt);
            }
        });

        btnRecuperar.setText("Recuperar Codigo Root");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        jLabel9.setText("Pregunta de seguridad: ");

        jLabel10.setText("Respuesta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iconVeri1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoPass2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCedula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoUser, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoPass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoRes, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(iconVeri1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addComponent(btnRecuperar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void campoCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCedulaKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 97 && k <= 122 || k >= 65 && k <= 255 || k >= 32 && k <= 47 || k >= 58 && k <= 64) {//Si el caracter ingresado es una letra
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
        JOptionPane.showMessageDialog(null, "No puede ingresar letras, ni carateres especiales!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_campoCedulaKeyTyped

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 32 && k <= 64 || k >= 91 && k <= 96 || k >= 123 && k <= 255) {//Si el caracter ingresado es numero
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
        JOptionPane.showMessageDialog(null, "No puede ingresar numeros, ni caracteres especiales!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_campoNombreKeyTyped

    private void campoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoKeyTyped
        // TODO add your handling code here:
        int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada

        if (k >= 32 && k <= 64 || k >= 91 && k <= 96 || k >= 123 && k <= 255) {//Si el caracter ingresado es una letra
        evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
        JOptionPane.showMessageDialog(null, "No puede ingresar numeros, ni caracteres especiales!!!", "Validando Datos",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_campoApellidoKeyTyped

    private void campoPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPassActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_campoPassActionPerformed

    private void campoPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPass2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoPass2ActionPerformed

    private void campoPass2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPass2KeyReleased
        // TODO add your handling code here:
        if (this.campoPass2.getText().equals(this.campoPass.getText())) {
            this.iconVeri1.setVisible(true);
        }else{
            this.iconVeri1.setVisible(false);
        }
    }//GEN-LAST:event_campoPass2KeyReleased

    private void campoPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPassMouseClicked
        // TODO add your handling code here:
        this.campoPass.setText("");
        if (this.campoPass.getText().equals("")) {
            this.iconVeri1.setVisible(false);   
        }
    }//GEN-LAST:event_campoPassMouseClicked

    private void campoPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPass2MouseClicked
        // TODO add your handling code here:
        this.campoPass2.setText("");
    }//GEN-LAST:event_campoPass2MouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nom,ape,cedu,user,pass,res,codRoot;
        int pre,sta;
        
        if (this.campoPass.getText().equals(this.campoPass2.getText())) {
            
            nom = this.campoNombre.getText();
            ape = this.campoApellido.getText();
            cedu = this.campoCedula.getText();
            user = this.campoUser.getText();
            pass = DigestUtils.md5Hex(this.campoPass.getText());
            codRoot = DigestUtils.md5Hex(this.campoCRoot.getText());
            pre  = this.comboPre.getSelectedIndex();
            res  = this.campoRes.getText();
            sta = ADMIN;
            
            
            Control_registroRoot cr = new Control_registroRoot(nom,ape,cedu,user,pass,codRoot,pre,res);
            Control_login cl = new Control_login(nom,ape,cedu,user,pass,pre,res,sta);
            if (nom.equals("") || !ape.equals("") || !cedu.equals("") || !user.equals("") || !pass.equals("") || pre!=0 || !res.equals("") || !codRoot.equals(""))
            {
                if (this.estadoUser == false) {
                    JOptionPane.showMessageDialog(null, "Existe un Usuario registrado con el mismo Username, por favor cambiar!!!", "Validando Datos",
                    JOptionPane.ERROR_MESSAGE);
                    this.campoUser.setText("");
                    this.revalidate();
                }else{
                    if(cr.ingresar_root() && cl.ingresar_login())
                    {
                        JOptionPane.showMessageDialog(null,"El usuario ROOT se registro con exito","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                        limpiar();

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Error al registar el usuario ROOT ","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
           else{
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios");  
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden, Por favor verificar¡ ","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void campoUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUserKeyReleased
        // TODO add your handling code here:
        Control_registroRoot cr = new Control_registroRoot(null,null,null,null,null,null,0,null);
        if (cr.consulta_loginUSER(this.campoUser.getText()) == null) {
            this.campoUser.setBorder(BorderFactory.createLineBorder(Color.GREEN));
            this.estadoUser = true;
        }else{
             this.campoUser.setBorder(BorderFactory.createLineBorder(Color.RED));
             this.estadoUser = false;
        }
    }//GEN-LAST:event_campoUserKeyReleased

    public void limpiar(){
        this.campoNombre.setText("");
        this.campoApellido.setText("");
        this.campoCedula.setText("");
        this.campoUser.setText("");
        this.campoPass.setText("");
        this.campoPass2.setText("");
        this.campoCRoot.setText("");
        this.comboPre.setSelectedIndex(0);
        this.campoRes.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_RegistroRoot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_RegistroRoot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRecuperar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JTextField campoApellido;
    public javax.swing.JTextField campoCRoot;
    public javax.swing.JTextField campoCedula;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JPasswordField campoPass;
    public javax.swing.JPasswordField campoPass2;
    public javax.swing.JTextField campoRes;
    public javax.swing.JTextField campoUser;
    public javax.swing.JComboBox<String> comboPre;
    public javax.swing.JLabel iconVeri1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
